name: build-overlay

on:
  workflow_dispatch:
  push:

jobs:
  build-overlay:
    runs-on: ubuntu-24.04
    env:
      ROS_DISTRO: one
      DEB_DISTRO: jammy
      UPSTREAM: https://raw.githubusercontent.com/v4hn/ros-o-builder/jammy-one/repository
    steps:
      - name: install Debian ROS packages
        run: |
          sudo add-apt-repository -y ppa:v-launchpad-jochen-sprickerhof-de/ros
          sudo apt update
      - uses: v4hn/ros-deb-builder-action@roso-noble
        with:
          ROS_DISTRO: ${{ env.ROS_DISTRO }}
          DEB_DISTRO: ${{ env.DEB_DISTRO }}
          REPOS_FILE: sources.repos
          ROSDEP_SOURCE: |
            rosdep.yaml
            ${{ env.UPSTREAM }}/local.yaml
          DEB_REPOSITORY: |
            deb [trusted=yes] ${{ env.UPSTREAM }} ./
          SBUILD_CONF: "$enable_network = 1;"
          CONTINUE_ON_ERROR: true
          PUSH_ON_ERROR: true
          SQUASH_HISTORY: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
